"""
Aggregate algorithm rankings across dataset types using pre-computed ranking CSVs.
This script reads the rankings_summary.csv files generated by generate_vegalite_plots.py
and aggregates them by dataset type to see which algorithms perform best for each type.
"""

import pandas as pd
import altair as alt
from pathlib import Path
import argparse
from collections import defaultdict

# Dataset type groupings
DATASET_TYPES = {
    'eeg_500': ['eeg_chan05_500', 'eeg_chan10_500', 'eeg_chan15_500', 
                'eeg_chan20_500', 'eeg_chan25_500', 'eeg_chan30_500'],
    'eeg_2500': ['eeg_chan05_2500', 'eeg_chan10_2500', 'eeg_chan15_2500',
                 'eeg_chan20_2500', 'eeg_chan25_2500', 'eeg_chan30_2500'],
    'eeg_10000': ['eeg_chan05_10000', 'eeg_chan10_10000', 'eeg_chan15_10000',
                  'eeg_chan20_10000', 'eeg_chan25_10000', 'eeg_chan30_10000'],
    'climate_awnd': ['climate_atl_awnd', 'climate_jfk_awnd', 'climate_lax_awnd',
                     'climate_ord_awnd', 'climate_sea_awnd', 'climate_slc_awnd'],
    'climate_prcp': ['climate_atl_prcp', 'climate_jfk_prcp', 'climate_lax_prcp',
                     'climate_ord_prcp', 'climate_sea_prcp', 'climate_slc_prcp'],
    'climate_tmax': ['climate_atl_tmax', 'climate_jfk_tmax', 'climate_lax_tmax',
                     'climate_ord_tmax', 'climate_sea_tmax', 'climate_slc_tmax'],
    'stock_price': ['stock_aapl_price', 'stock_amzn_price', 'stock_bac_price',
                    'stock_goog_price', 'stock_intc_price', 'stock_jpm_price',
                    'stock_msft_price', 'stock_tm_price', 'stock_tsla_price'],
    'stock_volume': ['stock_aapl_volume', 'stock_amzn_volume', 'stock_bac_volume',
                     'stock_goog_volume', 'stock_intc_volume', 'stock_jpm_volume',
                     'stock_msft_volume', 'stock_tm_volume', 'stock_tsla_volume'],
    'unemployment': ['unemployment_ag', 'unemployment_business', 'unemployment_construction',
                     'unemployment_edu_health', 'unemployment_finance', 'unemployment_govt',
                     'unemployment_hospitality', 'unemployment_info', 'unemployment_manufacturing',
                     'unemployment_mining', 'unemployment_other', 'unemployment_self_emp',
                     'unemployment_trade', 'unemployment_transport'],
    'flights': ['flights_daily', 'flights_monthly', 'flights_weekly'],
    'tourism': ['nz_tourist_annually', 'nz_tourist_monthly'],
    'crime': ['chi_homicide_monthly', 'chi_homicide_weekly'],
    'astro': ['astro_115_120', 'astro_115_123', 'astro_115_128',
              'astro_116_124', 'astro_116_134'],
}

def load_ranking_csv(dataset_name):
    """Load the rankings_summary.csv for a dataset"""
    csv_path = Path('plots') / dataset_name / 'rankings_summary.csv'
    if not csv_path.exists():
        print(f"  ⚠️  Missing: {csv_path}")
        return None
    return pd.read_csv(csv_path)

def aggregate_by_type(dataset_type, datasets):
    """Aggregate rankings across all datasets of a given type"""
    print(f"\n📊 Aggregating: {dataset_type}")
    print(f"   Datasets: {', '.join(datasets)}")
    
    all_rankings = []
    
    for dataset in datasets:
        df = load_ranking_csv(dataset)
        if df is not None:
            df['dataset'] = dataset
            all_rankings.append(df)
    
    if not all_rankings:
        print(f"  ❌ No data found for {dataset_type}")
        return None
    
    combined = pd.concat(all_rankings, ignore_index=True)
    
    # Aggregate: average rank per algorithm per metric across all datasets
    agg = combined.groupby(['metric', 'algorithm']).agg({
        'rank': 'mean',
        'mean_fc_score': 'mean',
        'std_fc_score': 'mean',
        'mean_pae': 'mean',
        'mean_metric_value': 'mean',
        'dataset': 'count'  # How many datasets contributed
    }).reset_index()
    
    agg.rename(columns={'dataset': 'num_datasets'}, inplace=True)
    
    # Re-rank based on average rank
    agg['avg_rank'] = agg.groupby('metric')['rank'].rank(method='dense').astype(int)
    agg = agg.sort_values(['metric', 'avg_rank'])
    
    print(f"  ✅ Aggregated {len(combined)} rows from {len(all_rankings)} datasets")
    
    return agg

def create_ranking_chart(df, dataset_type, metric=None):
    """Create a ranking visualization for a dataset type"""
    if metric:
        plot_df = df[df['metric'] == metric].copy()
        title = f'{dataset_type}: {metric} Rankings'
    else:
        # Overall: average rank across all metrics
        plot_df = df.groupby('algorithm').agg({
            'avg_rank': 'mean',
            'mean_fc_score': 'mean',
            'num_datasets': 'first'
        }).reset_index()
        plot_df['overall_rank'] = plot_df['avg_rank'].rank(method='dense').astype(int)
        plot_df = plot_df.sort_values('overall_rank')
        title = f'{dataset_type}: Overall Algorithm Rankings'
    
    # Color scale for algorithms
    algorithm_colors = alt.Scale(
        domain=['gaussian_filter', 'savitzky_golay_filter', 'mean_filter', 'median_filter',
                'butterworth_filter', 'chebyshev_filter', 'elliptical_filter', 'fft_cutoff_filter',
                'lttb_downsample', 'm4_downsample', 'minmaxlttb_downsample', 'uniform_subsample',
                'fpcs_downsample', 'rdp_downsample', 'asap_aggregator', 'bin_average_aggregator',
                'tda_downsample', 'max_filter', 'min_filter'],
        range=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', 
               '#e377c2', '#7f7f7f', '#bcbd22', '#17becf', '#aec7e8', '#ffbb78',
               '#98df8a', '#ff9896', '#c5b0d5', '#c49c94', '#f7b6d2', '#c7c7c7', '#dbdb8d']
    )
    
    if metric:
        chart = alt.Chart(plot_df).mark_bar().encode(
            x=alt.X('algorithm:N', 
                    title='Algorithm',
                    sort=alt.EncodingSortField(field='avg_rank', order='ascending')),
            y=alt.Y('mean_fc_score:Q', 
                    title='Average FC Score'),
            color=alt.Color('algorithm:N', scale=algorithm_colors, legend=None),
            tooltip=['algorithm:N', 
                     alt.Tooltip('avg_rank:Q', title='Rank'),
                     alt.Tooltip('mean_fc_score:Q', title='Avg FC Score', format='.3f'),
                     alt.Tooltip('mean_pae:Q', title='Avg PAE', format='.4f'),
                     alt.Tooltip('num_datasets:Q', title='# Datasets')]
        ).properties(
            width=800,
            height=400,
            title=title
        )
    else:
        rank_col = 'overall_rank' if 'overall_rank' in plot_df.columns else 'avg_rank'
        chart = alt.Chart(plot_df).mark_bar().encode(
            x=alt.X('algorithm:N', 
                    title='Algorithm',
                    sort=alt.EncodingSortField(field=rank_col, order='ascending')),
            y=alt.Y('mean_fc_score:Q', 
                    title='Average FC Score'),
            color=alt.Color('algorithm:N', scale=algorithm_colors, legend=None),
            tooltip=['algorithm:N', 
                     alt.Tooltip(f'{rank_col}:Q', title='Overall Rank'),
                     alt.Tooltip('mean_fc_score:Q', title='Avg FC Score', format='.3f')]
        ).properties(
            width=800,
            height=400,
            title=title
        )
    
    return chart

def main():
    parser = argparse.ArgumentParser(description='Aggregate algorithm rankings by dataset type')
    parser.add_argument('--type', type=str, 
                        help='Specific dataset type to process (e.g., eeg_500, climate_awnd)')
    parser.add_argument('--all', action='store_true',
                        help='Process all dataset types')
    parser.add_argument('--metric', type=str,
                        help='Specific metric to visualize (default: overall ranking)')
    
    args = parser.parse_args()
    
    if args.type:
        types_to_process = [args.type]
    elif args.all:
        types_to_process = list(DATASET_TYPES.keys())
    else:
        print("Please specify --type <name> or --all")
        return
    
    print(f"🎯 Processing {len(types_to_process)} dataset type(s)...")
    
    output_dir = Path('plots/dataset_type_rankings')
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for dataset_type in types_to_process:
        if dataset_type not in DATASET_TYPES:
            print(f"❌ Unknown dataset type: {dataset_type}")
            continue
        
        datasets = DATASET_TYPES[dataset_type]
        agg_df = aggregate_by_type(dataset_type, datasets)
        
        if agg_df is None:
            continue
        
        # Save aggregated CSV
        csv_path = output_dir / f'{dataset_type}_rankings.csv'
        agg_df.to_csv(csv_path, index=False)
        print(f"  💾 Saved: {csv_path}")
        
        # Create overall ranking chart
        overall_chart = create_ranking_chart(agg_df, dataset_type, metric=None)
        svg_path = output_dir / f'{dataset_type}_overall_ranking.svg'
        overall_chart.save(str(svg_path))
        print(f"  🎨 Saved: {svg_path}")
        
        # If specific metric requested, create that chart too
        if args.metric:
            if args.metric in agg_df['metric'].values:
                metric_chart = create_ranking_chart(agg_df, dataset_type, metric=args.metric)
                metric_svg_path = output_dir / f'{dataset_type}_{args.metric}_ranking.svg'
                metric_chart.save(str(metric_svg_path))
                print(f"  🎨 Saved: {metric_svg_path}")
            else:
                print(f"  ⚠️  Metric '{args.metric}' not found in data")
        
        # Print top 5 overall
        overall_ranks = agg_df.groupby('algorithm')['avg_rank'].mean().sort_values()
        print(f"\n  🏆 Top 5 algorithms for {dataset_type}:")
        for i, (algo, rank) in enumerate(overall_ranks.head(5).items(), 1):
            print(f"    {i}. {algo} (avg rank: {rank:.2f})")
    
    print(f"\n✅ Complete! Results saved to {output_dir}/")

if __name__ == '__main__':
    main()
